language: c
group: travis_latest
dist: bionic

git:
  depth: false
  quiet: true

os:
  - linux
  - osx
  
compiler:
  - clang
  - gcc

script:
  - make
  - sudo make install
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then make deb ; fi
  - .travis/test.sh
